# Generated by Django 4.1.5 on 2023-01-22 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItemFirstLvl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('text', models.TextField(null=True, verbose_name='Текст')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='url-slug')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Элемент первого уровня',
                'verbose_name_plural': 'Элементы первого уровня',
            },
        ),
        migrations.CreateModel(
            name='MenuItemSecondLvl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('text', models.TextField(null=True, verbose_name='Текст')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='url-slug')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='menuApp.menuitemfirstlvl')),
            ],
            options={
                'verbose_name': 'Элемент второго уровня',
                'verbose_name_plural': 'Элементы второго уровня',
            },
        ),
        migrations.CreateModel(
            name='MenuItemThirdLvl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('text', models.TextField(null=True, verbose_name='Текст')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='url-slug')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='menuApp.menuitemsecondlvl')),
            ],
            options={
                'verbose_name': 'Элемент третьего уровня',
                'verbose_name_plural': 'Элементы третьего уровня',
            },
        ),
    ]
