# Generated by Django 4.1.5 on 2023-01-22 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menuApp', '0003_alter_menuitemsecondlvl_parent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitemsecondlvl',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_lvl', to='menuApp.menuitemfirstlvl'),
        ),
        migrations.AlterField(
            model_name='menuitemthirdlvl',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='third_lvl', to='menuApp.menuitemsecondlvl'),
        ),
    ]
